import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "@/styles/globals.css"
import { ThemeProvider } from "@/providers/theme"
import Navbar from "@/components/navbar"
import ClerkAuthProvider from "@/providers/clerk"
import QueryProvider from "@/providers/queryClient"
import { Toaster } from "sonner"
const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

type children = { children: React.ReactNode }
export default function RootLayout({ children }: children) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryProvider>
            <ClerkAuthProvider>
              <Navbar />

              {children}
              <Toaster richColors />
            </ClerkAuthProvider>
          </QueryProvider>
        </ThemeProvider>
      </body>
    </html>
  )
}
